name: First-WorkFlow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest 
    steps:
      - name: Print Greetings
        run: echo "Hello World"
      - name: Greeting Confirmation
        run: echo "Done , Bye!"
